# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

gem: [jekyll-paginate, jekyll-gists, jemoji]

# Setup
title:            Fleptic
tagline:          'My home on the internet'
description:      '$ sudo apt-get reckt'

# Deployment URL values
url:              https://fleptic.eu/
baseurl:          https://fleptic.eu/

# Dev URL values
#url:              "/fleptic/"
#baseurl:          "/"

author:
  name:           'Koushtav Chakrabarty'
  url:            https://fleptic.eu

paginate:         3

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
#  url:            https://theillusionistmirage.github.io

plugins:
  - jemoji
  - jekyll-font-awesome

github_username:  TheIllusionistMirage
linkedin_username: koushtavc
email: koushtavc@gmail.com
