# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

gem: [jekyll-paginate, jekyll-gists, jemoji]

# Setup
title:            Fleptic
tagline:          'My home on the internet'
description:      'Welcome to my personal site!'
url:              https://theillusionistmirage.github.io/
baseurl:          https://theillusionistmirage.github.io/

author:
  name:           'Koushtav Chakrabarty'
  url:            https://fleptic.eu

paginate:         3

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
#  url:            https://theillusionistmirage.github.io
  
plugins:
  - jemoji
  - jekyll-font-awesome
  
github_username:  TheIllusionistMirage
linkedin_username: koushtavc
